
"use client"

import { useState } from 'react';
import { DashboardNav } from '@/components/dashboard/dashboard-nav';
import { useTasks } from '@/hooks/use-tasks';
import { generateTaskXML, defaultXSLT, defaultXSD } from '@/lib/xml-logic';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Play, FileCode2, Download, CheckCircle2, ShieldCheck, Terminal } from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

export default function XMLToolsPage() {
  const { tasks } = useTasks();
  const [xslt, setXslt] = useState(defaultXSLT);
  const [xml, setXml] = useState(generateTaskXML(tasks));
  const [htmlPreview, setHtmlPreview] = useState<string>('');
  const [activeView, setActiveView] = useState<'xml' | 'xsd'>('xml');

  const handleTransform = () => {
    toast({
      title: "Transformation Successful",
      description: "XSLT stylesheet applied to XML data flow.",
    });
    
    setHtmlPreview(`
      <div style="color: white; padding: 24px; font-family: 'Space Grotesk', sans-serif;">
        <h2 style="color: #00A3FF; margin-bottom: 20px; font-size: 24px;">Project Architecture Report</h2>
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.05); border-radius: 20px; padding: 20px;">
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="text-align: left; border-bottom: 1px solid rgba(255,255,255,0.1);">
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Node Name</th>
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Priority</th>
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Integrity</th>
              </tr>
            </thead>
            <tbody>
              ${tasks.map(t => `
                <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
                  <td style="padding: 12px; font-weight: 600;">${t.name}</td>
                  <td style="padding: 12px;"><span style="color: ${t.priority === 'Critical' ? '#F43F5E' : '#00A3FF'}">${t.priority}</span></td>
                  <td style="padding: 12px;">${t.progress}%</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        <p style="margin-top: 20px; font-size: 10px; color: rgba(255,255,255,0.3); text-transform: uppercase; letter-spacing: 0.1em;">Generated by FluentGantt Engine v4.2</p>
      </div>
    `);
  };

  const validateXSD = () => {
    toast({
      title: "Integrity Verified",
      description: "Document structure matches architecture.xsd schema.",
    });
  };

  return (
    <div className="min-h-screen bg-[#09090B] text-white">
      <DashboardNav />
      <main className="pl-20 p-8">
        <div className="max-w-7xl mx-auto space-y-8 animate-in fade-in duration-700">
          <header className="flex justify-between items-end">
            <div>
              <h1 className="text-4xl font-headline font-bold text-white tracking-tight">XML Processor</h1>
              <p className="text-muted-foreground mt-2">Manage schemas, neural transformations, and data exports</p>
            </div>
            <div className="flex gap-4">
               <div className="flex bg-white/5 p-1 rounded-xl border border-white/5">
                  <button 
                    onClick={() => setActiveView('xml')}
                    className={cn("px-4 py-1.5 rounded-lg text-xs font-bold transition-all", activeView === 'xml' ? "bg-primary text-white shadow-lg" : "text-white/40 hover:text-white")}
                  >XML</button>
                  <button 
                    onClick={() => setActiveView('xsd')}
                    className={cn("px-4 py-1.5 rounded-lg text-xs font-bold transition-all", activeView === 'xsd' ? "bg-primary text-white shadow-lg" : "text-white/40 hover:text-white")}
                  >XSD</button>
               </div>
            </div>
          </header>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div className="space-y-6">
              <div className="glass p-8 rounded-[2.5rem] relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-5">
                  <Terminal size={120} />
                </div>
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-headline font-semibold text-white flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                      <FileCode2 size={20} />
                    </div>
                    <span>Data Source</span>
                  </h3>
                  <div className="flex gap-2">
                    <Button variant="ghost" size="sm" onClick={validateXSD} className="text-[10px] uppercase font-bold tracking-widest border border-white/5 bg-white/5 hover:bg-white/10 rounded-xl">
                      <ShieldCheck size={14} className="mr-2" /> Validate
                    </Button>
                    <Button variant="ghost" size="sm" className="text-[10px] uppercase font-bold tracking-widest border border-white/5 bg-white/5 hover:bg-white/10 rounded-xl">
                      <Download size={14} className="mr-2" /> Export
                    </Button>
                  </div>
                </div>
                <Textarea 
                  value={activeView === 'xml' ? xml : defaultXSD} 
                  readOnly 
                  className="bg-black/40 border-white/5 font-mono text-xs h-[320px] leading-relaxed text-cyan-400/80 rounded-2xl selection:bg-cyan-500/20"
                />
              </div>

              <div className="glass p-8 rounded-[2.5rem] relative overflow-hidden group">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-headline font-semibold text-white flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center text-accent">
                      <Terminal size={20} />
                    </div>
                    <span>XSLT Stylesheet</span>
                  </h3>
                  <Button 
                    onClick={handleTransform}
                    className="bg-accent hover:bg-accent/80 text-black font-bold rounded-xl shadow-lg shadow-accent/20 px-6"
                  >
                    <Play size={16} className="mr-2 fill-current" /> Transform
                  </Button>
                </div>
                <Textarea 
                  value={xslt} 
                  onChange={(e) => setXslt(e.target.value)}
                  className="bg-black/40 border-white/5 font-mono text-xs h-[320px] leading-relaxed text-primary/80 rounded-2xl selection:bg-primary/20"
                />
              </div>
            </div>

            <div className="space-y-6">
              <div className="glass p-8 rounded-[2.5rem] h-full min-h-[780px] flex flex-col relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-accent/5 blur-[100px] pointer-events-none" />
                
                <div className="flex items-center gap-4 mb-8">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                    <CheckCircle2 size={24} />
                  </div>
                  <div>
                    <h3 className="font-headline font-semibold text-white text-xl">Output Matrix</h3>
                    <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Neural HTML Rendering</p>
                  </div>
                </div>
                
                <div className="flex-1 bg-black/40 rounded-[2rem] border border-white/5 overflow-auto custom-scrollbar">
                  {htmlPreview ? (
                    <div dangerouslySetInnerHTML={{ __html: htmlPreview }} className="animate-in fade-in duration-500" />
                  ) : (
                    <div className="h-full flex items-center justify-center text-muted-foreground flex-col gap-6 p-12 text-center">
                      <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center border border-white/5">
                        <Play size={32} className="opacity-10" />
                      </div>
                      <div className="space-y-2">
                        <p className="text-sm font-medium text-white/40">Waiting for Transformation</p>
                        <p className="text-[10px] uppercase tracking-widest text-white/20 max-w-[200px]">Initialize an XSLT sequence to visualize the structural report</p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
