
"use client"

import { useState } from 'react';
import { DashboardNav } from '@/components/dashboard/dashboard-nav';
import { useTasks } from '@/hooks/use-tasks';
import { generateTaskXML, defaultXSLT, defaultXSD } from '@/lib/xml-logic';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { 
  Play, 
  FileCode2, 
  Download, 
  CheckCircle2, 
  ShieldCheck, 
  Terminal, 
  Printer, 
  Copy, 
  ChevronDown, 
  ChevronUp,
  FileText
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';

export default function XMLToolsPage() {
  const { tasks } = useTasks();
  const [xslt, setXslt] = useState(defaultXSLT);
  const [xml, setXml] = useState(generateTaskXML(tasks));
  const [htmlPreview, setHtmlPreview] = useState<string>('');
  const [activeView, setActiveView] = useState<'xml' | 'xsd'>('xml');
  const [showAdvanced, setShowAdvanced] = useState(false);

  const handleTransform = () => {
    setXml(generateTaskXML(tasks)); // Refresh XML with latest data
    toast({
      title: "Report Generated",
      description: "Neural HTML transformation complete.",
    });
    
    setHtmlPreview(`
      <div style="color: white; padding: 24px; font-family: 'Space Grotesk', sans-serif;">
        <h2 style="color: #00A3FF; margin-bottom: 20px; font-size: 24px; font-weight: bold;">Project Architecture Report</h2>
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.05); border-radius: 20px; padding: 20px;">
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="text-align: left; border-bottom: 1px solid rgba(255,255,255,0.1);">
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Node Name</th>
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Priority</th>
                <th style="padding: 12px; color: rgba(255,255,255,0.5); font-size: 10px; text-transform: uppercase; letter-spacing: 0.2em;">Integrity</th>
              </tr>
            </thead>
            <tbody>
              ${tasks.map(t => `
                <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
                  <td style="padding: 12px; font-weight: 600;">${t.name}</td>
                  <td style="padding: 12px;"><span style="color: ${t.priority === 'Critical' ? '#F43F5E' : '#00A3FF'}">${t.priority}</span></td>
                  <td style="padding: 12px;">${t.progress}%</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        <p style="margin-top: 20px; font-size: 10px; color: rgba(255,255,255,0.3); text-transform: uppercase; letter-spacing: 0.1em;">Generated by FluentGantt Engine v4.2 • ${new Date().toLocaleDateString()}</p>
      </div>
    `);
  };

  const copyToClipboard = () => {
    toast({ title: "Copied", description: "Report HTML copied to clipboard." });
  };

  return (
    <div className="min-h-screen bg-[#09090B] text-white">
      <DashboardNav />
      <main className="pl-20 p-8">
        <div className="max-w-7xl mx-auto space-y-8 animate-in fade-in duration-700">
          <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div>
              <h1 className="text-4xl font-headline font-bold text-white tracking-tight">Report Center</h1>
              <p className="text-muted-foreground mt-2">Generate professional project documentation from your neural data</p>
            </div>
            <div className="flex gap-4">
              <Button 
                onClick={handleTransform}
                className="bg-primary hover:bg-primary/80 text-white font-bold rounded-xl shadow-lg shadow-primary/20 px-8 h-12"
              >
                <FileText size={18} className="mr-2" /> Generate Report
              </Button>
            </div>
          </header>

          <div className="grid grid-cols-1 gap-8">
            {/* Main Preview Area */}
            <div className="glass p-8 rounded-[2.5rem] min-h-[500px] flex flex-col relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 blur-[100px] pointer-events-none" />
              
              <div className="flex items-center justify-between mb-8">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                    <CheckCircle2 size={24} />
                  </div>
                  <div>
                    <h3 className="font-headline font-semibold text-white text-xl">Document Preview</h3>
                    <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Neural HTML Rendering</p>
                  </div>
                </div>
                
                {htmlPreview && (
                  <div className="flex gap-2">
                    <Button variant="ghost" size="sm" onClick={copyToClipboard} className="text-[10px] uppercase font-bold tracking-widest border border-white/5 bg-white/5 hover:bg-white/10 rounded-xl">
                      <Copy size={14} className="mr-2" /> Copy
                    </Button>
                    <Button variant="ghost" size="sm" className="text-[10px] uppercase font-bold tracking-widest border border-white/5 bg-white/5 hover:bg-white/10 rounded-xl">
                      <Printer size={14} className="mr-2" /> Print
                    </Button>
                  </div>
                )}
              </div>
              
              <div className="flex-1 bg-black/40 rounded-[2rem] border border-white/5 overflow-auto custom-scrollbar">
                {htmlPreview ? (
                  <div dangerouslySetInnerHTML={{ __html: htmlPreview }} className="animate-in fade-in duration-500" />
                ) : (
                  <div className="h-full flex items-center justify-center text-muted-foreground flex-col gap-6 p-12 text-center">
                    <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center border border-white/5">
                      <FileText size={32} className="opacity-10" />
                    </div>
                    <div className="space-y-2">
                      <p className="text-sm font-medium text-white/40">No report generated yet</p>
                      <p className="text-[10px] uppercase tracking-widest text-white/20 max-w-[280px]">
                        Click "Generate Report" to visualize your current project nodes in a professional format
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Advanced Section */}
            <Collapsible open={showAdvanced} onOpenChange={setShowAdvanced} className="glass p-6 rounded-[2rem] border-white/5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Terminal size={18} className="text-primary" />
                  <span className="text-sm font-bold uppercase tracking-widest text-white/60">Advanced Developer Tools</span>
                </div>
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" size="sm" className="rounded-full h-8 w-8 p-0">
                    {showAdvanced ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                  </Button>
                </CollapsibleTrigger>
              </div>

              <CollapsibleContent className="pt-6 space-y-6">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between px-2">
                      <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Source Data (XML/XSD)</h4>
                      <div className="flex bg-white/5 p-1 rounded-lg border border-white/5">
                        <button 
                          onClick={() => setActiveView('xml')}
                          className={cn("px-3 py-1 rounded-md text-[10px] font-bold transition-all", activeView === 'xml' ? "bg-primary text-white" : "text-white/40")}
                        >XML</button>
                        <button 
                          onClick={() => setActiveView('xsd')}
                          className={cn("px-3 py-1 rounded-md text-[10px] font-bold transition-all", activeView === 'xsd' ? "bg-primary text-white" : "text-white/40")}
                        >XSD</button>
                      </div>
                    </div>
                    <Textarea 
                      value={activeView === 'xml' ? xml : defaultXSD} 
                      readOnly 
                      className="bg-black/60 border-white/5 font-mono text-[10px] h-[250px] leading-relaxed text-cyan-400/60 rounded-2xl"
                    />
                  </div>

                  <div className="space-y-4">
                    <div className="flex items-center justify-between px-2">
                      <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Transformation Engine (XSLT)</h4>
                      <Button variant="ghost" size="sm" className="h-6 text-[9px] uppercase font-black bg-white/5">Reset to Default</Button>
                    </div>
                    <Textarea 
                      value={xslt} 
                      onChange={(e) => setXslt(e.target.value)}
                      className="bg-black/60 border-white/5 font-mono text-[10px] h-[250px] leading-relaxed text-primary/60 rounded-2xl"
                    />
                  </div>
                </div>
                <div className="flex justify-end gap-3">
                  <Button variant="outline" size="sm" className="rounded-xl border-white/10 text-xs">
                    <Download size={14} className="mr-2" /> Download XML
                  </Button>
                  <Button variant="outline" size="sm" className="rounded-xl border-white/10 text-xs">
                    <ShieldCheck size={14} className="mr-2" /> Validate Schema
                  </Button>
                </div>
              </CollapsibleContent>
            </Collapsible>
          </div>
        </div>
      </main>
    </div>
  );
}
